### PR TITLE
Business and Finance Recommendation Functions, Static Recommendation Page

### PR DESCRIPTION
**Pull request by florentianayuwono**
Create functions for business and finance recommendations.

Create static recommendation page using Accordion by Chakra-UI.

There will be more styling (need to add link, button, progress and other customizations) later.

### CODE REVIEW

**Comment by florentianayuwono** [comment]
So there is one thing about Chakra-UI that I need to ask you. In the documentation, it is mentioned that we need to set up the ChakraProvider at the root of out application. Hence the change in App.js in this commit history.

There are some changes that I noticed if we set up the ChakraProvider:

(Before) Without ChakraProvider

Dashboard styling is good
Screenshot (423)

Recommendation page is not so neat
Screenshot (424)

(After) With ChakraProvider

Recommendation page is neater
Screenshot (426)

But dashboard styling is kind of messed up (but should be able to be fixed later)
Screenshot (425)

Which one do you prefer?

**Comment by KamiliArsyad** [comment]
The Chakra provider was already used in the index.js file, the reason that it's not exactly _activated_ (`resetCSS={false}` in the index.js file)in a few cases is because the dashboard styling got messed up the moment it is set to the default (true).

This is because the dashboard styling is heavily reliant on the index.css file (and I think there are a lot of styles that got overridden by the previous index.css file in the recommendation page, too). tl;dr: the reason some stuff becomes ugly when we let chakra provider handles everything is because the previous style in index.css got overridden by Chakra, and the reason some stuff is uglier without chakra provider is because the chakra provider is overridden by index.css.

Best way to handle this I think is just to set the `resetCSS` prop of ChakraProvider in `index.js` to true, and then edit the dashboard styling later.

**Review by KamiliArsyad — APPROVED** [review]
Edited index.js and app.js. All good now and can merge.

**Comment by florentianayuwono** [comment]
I noticed that the problem is not only in the Dashboard. For example the Login, Register and other pages now, the icons with the text does not align horizontally. Also cannot bring the icons to the center. I have tried edit using HStack (Chakra-UI) and align-center (Bootstrap) but seems like not working (?)

**Comment by KamiliArsyad** [comment]
I have fixed the problem now in the frontend-feature branch. All the global default stylings are neatly packaged inside the theme folder.

**Comment by KamiliArsyad** [comment]
As for the icons, I think there's an align props in chakra for aligning things. I have tried using the Stack component and it seems to work in aligning things on the center.

**Comment by florentianayuwono** [comment]
Hmm wait I have made some styling changes and UI improvement (mostly margin and alignment). So is it like git merge frontend-feature in my current branch to see the changes? Have u sync changes in your branch?

**Comment by florentianayuwono** [comment]
I have tried merging changes from frontend-feature, but I still cannot use HStack in for example, Login page, to stack the icon and the Login text?

**Comment by KamiliArsyad** [comment]
Oh right hm what is going on haha

**Comment by florentianayuwono** [comment]
It's okay, I guess we can worry about that during the extension period haha. For now, is the Recommendation page gonna be static only or can we actually customize the recommendation display per business?

**Comment by KamiliArsyad** [comment]
We can customize stuff per business but there's a lot of state managements need to be done so I'll try working on that first

**Pull request merged**
